// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentId } from "./AgentId";
import type { GroupId } from "./GroupId";
import type { Resource } from "./Resource";

/**
 * Access restrictions for routes and structures.
 */
export type AccessControlList = { 
/**
 * Agents explicitly allowed access.
 */
allowed_agents: Array<AgentId>, 
/**
 * Groups explicitly allowed access.
 */
allowed_groups: Array<GroupId>, 
/**
 * Agents explicitly denied access.
 */
denied_agents: Array<AgentId>, 
/**
 * If true, open to all agents regardless of allow/deny lists.
 */
public: boolean, 
/**
 * Optional toll cost required for passage.
 */
toll_cost: { [key in Resource]?: number } | null, };
