// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionType } from "./ActionType";
import type { JsonValue } from "../serde_json/JsonValue";

/**
 * Details for a successful action event.
 */
export type ActionSucceededDetails = { 
/**
 * The type of action that succeeded.
 */
action_type: ActionType, 
/**
 * Action-specific parameters.
 */
parameters: JsonValue, 
/**
 * The outcome of the action.
 */
outcome: JsonValue, };
