// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";
import type { Resource } from "./Resource";

/**
 * The outcome of a successfully executed action.
 *
 * This is a generic container -- the actual payload depends on the action
 * type and is stored as a JSON value.
 */
export type ActionOutcome = { 
/**
 * Resources gained or spent as a result of the action.
 */
resource_changes: { [key in Resource]?: bigint }, 
/**
 * Energy spent on the action.
 */
energy_spent: number, 
/**
 * Skill experience gained.
 */
skill_xp: { [key in string]?: number }, 
/**
 * Additional outcome-specific data.
 */
details: JsonValue, };
