// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionOutcome } from "./ActionOutcome";
import type { ActionType } from "./ActionType";
import type { AgentId } from "./AgentId";
import type { RejectionDetails } from "./RejectionDetails";

/**
 * The result returned to an agent after the resolution phase.
 */
export type ActionResult = { 
/**
 * The tick of the action.
 */
tick: bigint, 
/**
 * The agent who acted.
 */
agent_id: AgentId, 
/**
 * The action that was attempted.
 */
action_type: ActionType, 
/**
 * Whether the action succeeded.
 */
success: boolean, 
/**
 * Success details (present only if `success` is true).
 */
outcome: ActionOutcome | null, 
/**
 * Failure details (present only if `success` is false).
 */
rejection: RejectionDetails | null, 
/**
 * Observable consequences of the action.
 */
side_effects: Array<string>, };
