// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionType } from "./ActionType";
import type { JsonValue } from "../serde_json/JsonValue";
import type { RejectionReason } from "./RejectionReason";

/**
 * Details for a rejected action event.
 */
export type ActionRejectedDetails = { 
/**
 * The type of action that was rejected.
 */
action_type: ActionType, 
/**
 * Action-specific parameters.
 */
parameters: JsonValue, 
/**
 * Why the action was rejected.
 */
reason: RejectionReason, 
/**
 * Additional context about the rejection.
 */
reason_details: JsonValue, };
