// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An action that an agent can submit to the World Engine.
 */
export type ActionType = "Gather" | "Eat" | "Drink" | "Rest" | "Move" | "Build" | "Repair" | "Demolish" | "ImproveRoute" | "Communicate" | "Broadcast" | "TradeOffer" | "TradeAccept" | "TradeReject" | "FormGroup" | "Teach" | "FarmPlant" | "FarmHarvest" | "Craft" | "Mine" | "Smelt" | "Write" | "Read" | "Claim" | "Legislate" | "Enforce" | "Reproduce" | "NoAction";
