// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionParameters } from "./ActionParameters";
import type { ActionType } from "./ActionType";
import type { AgentId } from "./AgentId";

/**
 * An action submitted by an agent to the World Engine for validation
 * and execution.
 */
export type ActionRequest = { 
/**
 * The agent submitting this action.
 */
agent_id: AgentId, 
/**
 * The current tick number.
 */
tick: bigint, 
/**
 * The type of action being taken.
 */
action_type: ActionType, 
/**
 * Action-specific data.
 */
parameters: ActionParameters, 
/**
 * Real-world submission timestamp.
 */
submitted_at: string, };
