// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentId } from "./AgentId";
import type { GroupId } from "./GroupId";
import type { LocationId } from "./LocationId";
import type { StructureId } from "./StructureId";

/**
 * The target entity of a freeform or targeted action.
 *
 * Used by [`FreeformAction`] and by conflict/diplomacy action parameters
 * to identify what the action is directed at.
 */
export type ActionTarget = { "Agent": AgentId } | { "Location": LocationId } | { "Structure": StructureId } | { "Resource": string } | { "Group": GroupId };
