// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentId } from "./AgentId";
import type { FreeformAction } from "./FreeformAction";
import type { GroupId } from "./GroupId";
import type { LocationId } from "./LocationId";
import type { Resource } from "./Resource";
import type { RuleId } from "./RuleId";
import type { StructureId } from "./StructureId";
import type { StructureType } from "./StructureType";
import type { TradeId } from "./TradeId";

/**
 * Action-specific parameters submitted alongside an [`ActionRequest`].
 *
 * Each variant corresponds to one [`ActionType`] and carries the data
 * needed to validate and execute that action.
 */
export type ActionParameters = { "Gather": { 
/**
 * The resource to collect.
 */
resource: Resource, } } | { "Eat": { 
/**
 * The food resource to consume from inventory.
 */
food_type: Resource, } } | "Drink" | "Rest" | { "Move": { 
/**
 * The destination location.
 */
destination: LocationId, } } | { "Build": { 
/**
 * The type of structure to build.
 */
structure_type: StructureType, } } | { "Repair": { 
/**
 * The structure to repair.
 */
structure_id: StructureId, } } | { "Demolish": { 
/**
 * The structure to demolish.
 */
structure_id: StructureId, } } | { "ImproveRoute": { 
/**
 * The route to improve (identified by destination).
 */
destination: LocationId, } } | { "Communicate": { 
/**
 * The agent to send a message to.
 */
target_agent: AgentId, 
/**
 * Message content (max 500 chars).
 */
message: string, } } | { "Broadcast": { 
/**
 * Message content (max 500 chars).
 */
message: string, } } | { "TradeOffer": { 
/**
 * The agent to propose a trade to.
 */
target_agent: AgentId, 
/**
 * Resources offered.
 */
offer: { [key in Resource]?: number }, 
/**
 * Resources requested in return.
 */
request: { [key in Resource]?: number }, } } | { "TradeAccept": { 
/**
 * The trade to accept.
 */
trade_id: TradeId, } } | { "TradeReject": { 
/**
 * The trade to reject.
 */
trade_id: TradeId, } } | { "FormGroup": { 
/**
 * Proposed group name.
 */
name: string, 
/**
 * Agent IDs invited to join the group.
 */
invited_members: Array<AgentId>, } } | { "Teach": { 
/**
 * The agent to teach.
 */
target_agent: AgentId, 
/**
 * The knowledge concept to teach.
 */
knowledge: string, } } | "FarmPlant" | "FarmHarvest" | { "Craft": { 
/**
 * What to craft (resource output).
 */
output: Resource, } } | "Mine" | "Smelt" | { "Write": { 
/**
 * Knowledge to persist to the library.
 */
knowledge: string, } } | { "Read": { 
/**
 * Knowledge to retrieve from the library.
 */
knowledge: string, } } | { "Claim": { 
/**
 * The structure to claim.
 */
structure_id: StructureId, } } | { "Legislate": { 
/**
 * Display name for the rule or law.
 */
rule_name: string, 
/**
 * Description of what the rule mandates or prohibits.
 */
rule_description: string, 
/**
 * The group this rule applies to.
 */
group_id: GroupId, } } | { "Enforce": { 
/**
 * The agent to enforce against.
 */
target_agent: AgentId, 
/**
 * The rule being enforced (by ID).
 */
rule_id: RuleId, 
/**
 * Description of the consequence being applied.
 */
consequence: string, } } | { "Reproduce": { 
/**
 * The partner agent.
 */
partner_agent: AgentId, } } | { "Steal": { 
/**
 * The agent to steal from.
 */
target_agent: AgentId, 
/**
 * The resource to steal.
 */
resource: Resource, } } | { "Attack": { 
/**
 * The agent to attack.
 */
target_agent: AgentId, } } | { "Intimidate": { 
/**
 * The agent to intimidate.
 */
target_agent: AgentId, } } | { "Propose": { 
/**
 * The group to propose to.
 */
group_id: GroupId, 
/**
 * Description of the proposal.
 */
proposal: string, } } | { "Vote": { 
/**
 * The group the vote is for.
 */
group_id: GroupId, 
/**
 * Whether the agent votes in favor.
 */
in_favor: boolean, } } | { "Marry": { 
/**
 * The agent to marry.
 */
partner_agent: AgentId, } } | { "Divorce": { 
/**
 * The agent to divorce.
 */
partner_agent: AgentId, } } | { "Conspire": { 
/**
 * The agents to conspire with.
 */
co_conspirators: Array<AgentId>, 
/**
 * The secret plan.
 */
plan: string, } } | { "Pray": { 
/**
 * Optional description of what the agent prays about.
 */
intent: string | null, } } | { "Freeform": FreeformAction } | "NoAction";
