// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LocationId } from "./LocationId";
import type { Resource } from "./Resource";

/**
 * Lightweight snapshot of agent state captured at event time.
 */
export type AgentStateSnapshot = { 
/**
 * Energy at event time.
 */
energy: number, 
/**
 * Health at event time.
 */
health: number, 
/**
 * Hunger at event time.
 */
hunger: number, 
/**
 * Age in ticks at event time.
 */
age: number, 
/**
 * Location at event time.
 */
location_id: LocationId, 
/**
 * Inventory summary at event time.
 */
inventory_summary: { [key in Resource]?: number }, };
