// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentId } from "./AgentId";
import type { Personality } from "./Personality";

/**
 * Immutable agent identity established at creation.
 */
export type Agent = { 
/**
 * Unique agent identifier.
 */
id: AgentId, 
/**
 * Display name, unique within the simulation.
 */
name: string, 
/**
 * Tick when the agent entered the simulation.
 */
born_at_tick: bigint, 
/**
 * Tick when the agent died (`None` if alive).
 */
died_at_tick: bigint | null, 
/**
 * How the agent died, if applicable.
 */
cause_of_death: string | null, 
/**
 * First parent (if reproduced; `None` for seed agents).
 */
parent_a: AgentId | null, 
/**
 * Second parent (if reproduced; `None` for seed agents).
 */
parent_b: AgentId | null, 
/**
 * Generation number (0 for seed agents).
 */
generation: number, 
/**
 * Immutable personality vector.
 */
personality: Personality, 
/**
 * Real-world creation time.
 */
created_at: string, };
