// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Resource } from "./Resource";
import type { StructureId } from "./StructureId";

/**
 * Details for an agent death event.
 */
export type AgentDiedDetails = { 
/**
 * Cause of death (starvation, old\_age, injury).
 */
cause: string, 
/**
 * Age at time of death in ticks.
 */
final_age: number, 
/**
 * Inventory dropped at the death location.
 */
inventory_dropped: { [key in Resource]?: number }, 
/**
 * Structures that lost their owner.
 */
structures_orphaned: Array<StructureId>, };
