// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentId } from "./AgentId";
import type { LocationId } from "./LocationId";
import type { MemoryEntry } from "./MemoryEntry";
import type { Resource } from "./Resource";

/**
 * Mutable state of an agent that changes each tick.
 */
export type AgentState = { 
/**
 * Reference to the agent this state belongs to.
 */
agent_id: AgentId, 
/**
 * Current energy (0--100).
 */
energy: number, 
/**
 * Current health (0--100).
 */
health: number, 
/**
 * Current hunger level (0--100).
 */
hunger: number, 
/**
 * Current thirst level (0--100).
 */
thirst: number, 
/**
 * Current age in ticks.
 */
age: number, 
/**
 * The tick when the agent entered the simulation.
 *
 * Seed agents have `born_at_tick = 0`. Child agents born via
 * reproduction have `born_at_tick > 0`. Used for maturity checks.
 */
born_at_tick: bigint, 
/**
 * Current location.
 */
location_id: LocationId, 
/**
 * Travel destination, if in transit.
 */
destination_id: LocationId | null, 
/**
 * Ticks remaining until arrival (0 if not traveling).
 */
travel_progress: number, 
/**
 * Carried resources.
 */
inventory: { [key in Resource]?: number }, 
/**
 * Maximum carry weight.
 */
carry_capacity: number, 
/**
 * Set of known concepts (knowledge base).
 */
knowledge: Array<string>, 
/**
 * Skill name to level mapping.
 */
skills: { [key in string]?: number }, 
/**
 * Skill name to experience points mapping.
 */
skill_xp: { [key in string]?: number }, 
/**
 * Active goals (max 5).
 */
goals: Array<string>, 
/**
 * Social graph: agent ID to relationship score.
 */
relationships: { [key in AgentId]?: string }, 
/**
 * Agent's memory entries.
 */
memory: Array<MemoryEntry>, };
