// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The intent of a combat action.
 */
export type CombatIntent = "Intimidate" | "Attack";
