// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentId } from "./AgentId";
import type { CombatIntent } from "./CombatIntent";
import type { LocationId } from "./LocationId";

/**
 * Details for a combat initiated event.
 *
 * Emitted at the start of a combat encounter, before resolution.
 * All agents at the location can observe this in their next perception.
 */
export type CombatInitiatedDetails = { 
/**
 * The agent who started the fight.
 */
attacker_id: AgentId, 
/**
 * The agent being attacked.
 */
defender_id: AgentId, 
/**
 * The type of combat action.
 */
intent: CombatIntent, 
/**
 * The location where combat occurred.
 */
location_id: LocationId, };
