// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentId } from "./AgentId";
import type { CombatIntent } from "./CombatIntent";
import type { LocationId } from "./LocationId";
import type { Resource } from "./Resource";

/**
 * Details for a combat resolved event.
 *
 * Emitted after combat resolution with all consequences applied.
 * Includes damage dealt, energy spent, and any loot transferred.
 */
export type CombatResolvedDetails = { 
/**
 * The agent who initiated the combat.
 */
attacker_id: AgentId, 
/**
 * The defending agent.
 */
defender_id: AgentId, 
/**
 * The intent of the combat action.
 */
intent: CombatIntent, 
/**
 * The winner of the combat (`None` if a draw).
 */
winner: AgentId | null, 
/**
 * Health damage dealt to the attacker.
 */
attacker_damage: number, 
/**
 * Health damage dealt to the defender.
 */
defender_damage: number, 
/**
 * Energy spent by the attacker.
 */
attacker_energy_cost: number, 
/**
 * Energy spent by the defender.
 */
defender_energy_cost: number, 
/**
 * Resources looted by the winner from the loser.
 */
loot_transferred: { [key in Resource]?: number }, 
/**
 * Whether the attacker died as a result of combat.
 */
attacker_died: boolean, 
/**
 * Whether the defender died as a result of combat.
 */
defender_died: boolean, 
/**
 * The location where combat occurred.
 */
location_id: LocationId, };
