// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Resource } from "./Resource";

/**
 * Economic metrics for a world snapshot.
 */
export type EconomyStats = { 
/**
 * Total resources across the entire simulation.
 */
total_resources: { [key in Resource]?: number }, 
/**
 * Resources currently held by agents.
 */
resources_in_circulation: { [key in Resource]?: number }, 
/**
 * Resources at location nodes.
 */
resources_at_nodes: { [key in Resource]?: number }, 
/**
 * Number of trades completed this tick.
 */
trades_this_tick: number, 
/**
 * Wealth inequality coefficient (0.0 = perfect equality, 1.0 = maximum inequality).
 */
gini_coefficient: string, };
