// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentId } from "./AgentId";
import type { GroupId } from "./GroupId";
import type { RuleId } from "./RuleId";

/**
 * Details for an enforcement applied event.
 *
 * Emitted when an agent enforces a governance rule against a target agent.
 * The consequence is social/reputational rather than mechanically binding.
 */
export type EnforcementAppliedDetails = { 
/**
 * The rule being enforced.
 */
rule_id: RuleId, 
/**
 * The agent performing the enforcement.
 */
enforcer: AgentId, 
/**
 * The agent the rule is being enforced against.
 */
target: AgentId, 
/**
 * The group whose authority backs this enforcement.
 */
group_id: GroupId, 
/**
 * A description of the consequence applied.
 */
consequence: string, };
