// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The type of entity participating in a ledger transfer.
 */
export type EntityType = "Agent" | "Location" | "Structure" | "World" | "Void";
