// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The current civilizational era, determined by emergent agent behavior.
 */
export type Era = "Primitive" | "Tribal" | "Agricultural" | "Settlement" | "Bronze" | "Iron" | "Classical" | "Medieval" | "Industrial" | "Modern";
