// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentId } from "./AgentId";
import type { AgentStateSnapshot } from "./AgentStateSnapshot";
import type { EventId } from "./EventId";
import type { EventType } from "./EventType";
import type { JsonValue } from "../serde_json/JsonValue";
import type { LocationId } from "./LocationId";
import type { WorldContext } from "./WorldContext";

/**
 * An immutable event recorded in the event store.
 *
 * Events are the source of truth for the simulation's history. State can
 * be reconstructed by replaying the event log.
 */
export type Event = { 
/**
 * Unique event identifier.
 */
id: EventId, 
/**
 * The tick when this event occurred.
 */
tick: bigint, 
/**
 * The category of event.
 */
event_type: EventType, 
/**
 * The primary agent involved, if any.
 */
agent_id: AgentId | null, 
/**
 * The location where the event occurred, if applicable.
 */
location_id: LocationId | null, 
/**
 * Type-specific payload serialized as JSON.
 */
details: JsonValue, 
/**
 * Agent state at the time of the event, if applicable.
 */
agent_state_snapshot: AgentStateSnapshot | null, 
/**
 * World-level context at the time of the event.
 */
world_context: WorldContext, 
/**
 * Real-world timestamp when the event was created.
 */
created_at: string, };
