// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A type of event recorded in the event store.
 */
export type EventType = "TickStart" | "TickEnd" | "AgentBorn" | "AgentDied" | "ActionSubmitted" | "ActionSucceeded" | "ActionRejected" | "ResourceGathered" | "ResourceConsumed" | "TradeCompleted" | "TradeFailed" | "StructureBuilt" | "StructureDestroyed" | "StructureRepaired" | "RouteImproved" | "RouteDegraded" | "LocationDiscovered" | "KnowledgeDiscovered" | "KnowledgeTaught" | "MessageSent" | "GroupFormed" | "RelationshipChanged" | "StructureClaimed" | "RuleCreated" | "EnforcementApplied" | "WeatherChanged" | "SeasonChanged" | "TheftOccurred" | "TheftFailed" | "CombatInitiated" | "CombatResolved" | "LedgerAnomaly";
