// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionTarget } from "./ActionTarget";
import type { JsonValue } from "../serde_json/JsonValue";

/**
 * A novel action proposed by an agent beyond the base action catalog.
 *
 * Agents submit freeform actions when they want to do something not covered
 * by the fixed `ActionType` enum. The feasibility evaluator in
 * `emergence-core` determines whether the action is physically possible.
 *
 * ## Examples
 *
 * - "I want to pray at the river" -- category "pray", target `Location`
 * - "I want to steal berries from Alpha" -- category "steal", target `Agent`
 * - "I want to sing a song" -- category "social", target `None`
 */
export type FreeformAction = { 
/**
 * What the agent wants to do, in natural language.
 */
intent: string, 
/**
 * The type/category of action (steal, pray, marry, attack, etc.).
 */
action_category: string, 
/**
 * Target entity (agent, location, structure, or resource).
 */
target: ActionTarget | null, 
/**
 * Additional parameters the agent specified.
 */
parameters: { [key in string]?: JsonValue }, };
