// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentId } from "./AgentId";
import type { GroupId } from "./GroupId";

/**
 * A social group formed by agents.
 *
 * Groups are created via the `FormGroup` action and represent voluntary
 * associations of agents with a shared identity. All members must be
 * co-located at formation and have a relationship score above 0.3 with
 * the founder.
 */
export type Group = { 
/**
 * Unique group identifier.
 */
id: GroupId, 
/**
 * Display name of the group.
 */
name: string, 
/**
 * The agent who founded the group.
 */
founder: AgentId, 
/**
 * All current members (including the founder).
 */
members: Array<AgentId>, 
/**
 * The tick when the group was formed.
 */
formed_at_tick: bigint, };
