// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentId } from "./AgentId";
import type { GroupId } from "./GroupId";

/**
 * Details for a group formation event.
 *
 * Emitted when agents successfully form a new social group.
 */
export type GroupFormedDetails = { 
/**
 * Unique identifier for the new group.
 */
group_id: GroupId, 
/**
 * Display name of the group.
 */
group_name: string, 
/**
 * The agent who founded the group.
 */
founder: AgentId, 
/**
 * All members of the group (including the founder).
 */
members: Array<AgentId>, 
/**
 * The tick when the group was formed.
 */
tick: bigint, };
