// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The cause of a relationship score change between two agents.
 *
 * Used to track why a relationship evolved, enabling richer social
 * dynamics and event logging.
 */
export type InteractionCause = "Trade" | "TradeFailed" | "Teaching" | "Communication" | "Conflict";
