// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A route the agent knows about from their current location.
 */
export type KnownRoute = { 
/**
 * Destination location UUID (use this in Move actions).
 */
destination_id: string, 
/**
 * Destination location name.
 */
destination: string, 
/**
 * Travel cost as a formatted string (e.g. "3 ticks").
 */
cost: string, 
/**
 * Path quality description (e.g. "dirt trail").
 */
path_type: string, 
/**
 * Key resources available at the destination (fuzzy quantities).
 */
resources_hint: string, };
