// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentId } from "./AgentId";

/**
 * Details for a knowledge taught event between two agents.
 */
export type KnowledgeTaughtDetails = { 
/**
 * The concept that was taught.
 */
knowledge: string, 
/**
 * The agent who taught the concept.
 */
teacher_id: AgentId, 
/**
 * The agent who received the concept.
 */
student_id: AgentId, 
/**
 * Whether the teaching was successful.
 */
success: boolean, };
