// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Details for a knowledge discovered event.
 */
export type KnowledgeDiscoveredDetails = { 
/**
 * The concept that was discovered.
 */
knowledge: string, 
/**
 * How it was discovered (experimentation, observation, accidental).
 */
method: string, 
/**
 * Prerequisite concepts.
 */
prerequisites: Array<string>, };
