// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The category of a resource transfer in the central ledger.
 */
export type LedgerEntryType = "Regeneration" | "Gather" | "Consume" | "Transfer" | "Build" | "Salvage" | "Decay" | "Drop" | "Pickup";
