// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Unique identifier for a ledger entry (resource transfer record).
 */
export type LedgerEntryId = string;
