// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntityType } from "./EntityType";
import type { LedgerEntryId } from "./LedgerEntryId";
import type { LedgerEntryType } from "./LedgerEntryType";
import type { Resource } from "./Resource";

/**
 * A single entry in the central ledger tracking all resource transfers.
 *
 * Every resource movement in the simulation produces a ledger entry.
 * The ledger must balance at the end of every tick (conservation law).
 */
export type LedgerEntry = { 
/**
 * Unique entry identifier.
 */
id: LedgerEntryId, 
/**
 * The tick when this transfer occurred.
 */
tick: bigint, 
/**
 * The category of transfer.
 */
entry_type: LedgerEntryType, 
/**
 * Source entity, if any (`None` for world-sourced regeneration).
 */
from_entity: string | null, 
/**
 * Type of the source entity.
 */
from_entity_type: EntityType | null, 
/**
 * Destination entity, if any (`None` for void-consumed resources).
 */
to_entity: string | null, 
/**
 * Type of the destination entity.
 */
to_entity_type: EntityType | null, 
/**
 * The resource being transferred.
 */
resource: Resource, 
/**
 * Quantity transferred (always positive; uses [`Decimal`] for financial-grade precision).
 */
quantity: string, 
/**
 * Reason for the transfer (e.g. `"GATHER"`, `"TRADE"`, `"BUILD"`).
 */
reason: string, 
/**
 * Related entity such as a trade or structure ID.
 */
reference_id: string | null, 
/**
 * Real-world timestamp.
 */
created_at: string, };
