// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Resource } from "./Resource";

/**
 * Aggregate effects of all structures at a location.
 *
 * Computed from the set of standing structures to determine bonuses
 * for agents resting, weather protection, production output, and
 * additional storage capacity.
 */
export type LocationEffects = { 
/**
 * Whether any structure at the location provides weather protection.
 */
weather_protection: boolean, 
/**
 * The best rest bonus multiplier available (as percentage, 100 = no bonus).
 */
best_rest_bonus_pct: number, 
/**
 * Total additional storage slots provided by structures.
 */
total_storage_slots: number, 
/**
 * Whether at least one shelter structure exists.
 */
has_shelter: boolean, 
/**
 * Whether a campfire (or fire source) exists.
 */
has_fire: boolean, 
/**
 * Resources produced per tick by structures at this location.
 */
production: { [key in Resource]?: number }, };
