// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentId } from "./AgentId";
import type { LocationId } from "./LocationId";
import type { Resource } from "./Resource";
import type { ResourceNode } from "./ResourceNode";

/**
 * A location node in the world graph.
 */
export type Location = { 
/**
 * Unique location identifier.
 */
id: LocationId, 
/**
 * Display name.
 */
name: string, 
/**
 * Region this location belongs to.
 */
region: string, 
/**
 * Category (natural, settlement, etc.).
 */
location_type: string, 
/**
 * Narrative description.
 */
description: string, 
/**
 * Maximum number of agents.
 */
capacity: number, 
/**
 * Resource availability at this location.
 */
base_resources: { [key in Resource]?: ResourceNode }, 
/**
 * Agents who know about this location.
 */
discovered_by: Array<AgentId>, 
/**
 * Real-world creation time.
 */
created_at: string, };
