// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemoryTier } from "./MemoryTier";

/**
 * A single memory stored by an agent.
 */
export type MemoryEntry = { 
/**
 * The tick when the memory was formed.
 */
tick: bigint, 
/**
 * Category of the memory (action, observation, communication, etc.).
 */
memory_type: string, 
/**
 * Human-readable description of what happened.
 */
summary: string, 
/**
 * Related entity identifiers.
 */
entities: Array<string>, 
/**
 * Retention importance (0.0 to 1.0). Higher means more likely retained.
 */
emotional_weight: string, 
/**
 * Which retention tier this memory belongs to.
 */
tier: MemoryTier, };
