// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentId } from "./AgentId";
import type { LocationId } from "./LocationId";

/**
 * A message stored on a location's message board in Dragonfly.
 *
 * Covers both direct (`communicate`) and broadcast messages. Direct
 * messages have a non-`None` `recipient_id`. Broadcast messages have
 * `is_broadcast == true` and `recipient_id == None`.
 *
 * Messages expire after a configurable number of ticks (default 10).
 */
export type Message = { 
/**
 * The agent who sent the message.
 */
sender_id: AgentId, 
/**
 * Display name of the sender (for perception rendering).
 */
sender_name: string, 
/**
 * The intended recipient, if this is a direct message.
 */
recipient_id: AgentId | null, 
/**
 * Message content (max 500 characters).
 */
content: string, 
/**
 * The tick when the message was sent.
 */
tick: bigint, 
/**
 * Whether this is a broadcast (visible to all at the location).
 */
is_broadcast: boolean, 
/**
 * The location where the message was posted.
 */
location_id: LocationId, };
