// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The quality of a route between two locations.
 */
export type PathType = "None" | "DirtTrail" | "WornPath" | "Road" | "Highway";
