// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentId } from "./AgentId";
import type { LocationId } from "./LocationId";
import type { Resource } from "./Resource";
import type { TradeId } from "./TradeId";

/**
 * A pending trade between two agents stored in `Dragonfly`.
 *
 * Created when an agent submits a [`TradeOffer`] action. The trade remains
 * pending until the target agent accepts, rejects, or the offer expires
 * after `expires_at_tick`.
 *
 * [`TradeOffer`]: crate::ActionType::TradeOffer
 */
export type PendingTrade = { 
/**
 * Unique trade identifier.
 */
trade_id: TradeId, 
/**
 * Agent who proposed the trade.
 */
offerer_id: AgentId, 
/**
 * Agent who must accept or reject.
 */
target_id: AgentId, 
/**
 * Resources the offerer is giving.
 */
offered_resources: { [key in Resource]?: number }, 
/**
 * Resources the offerer is requesting in return.
 */
requested_resources: { [key in Resource]?: number }, 
/**
 * Tick when the trade was created.
 */
created_at_tick: bigint, 
/**
 * Tick when the trade expires if not acted upon.
 */
expires_at_tick: bigint, 
/**
 * Location where both agents were when the trade was proposed.
 */
location_id: LocationId, };
