// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KnownRoute } from "./KnownRoute";
import type { Personality } from "./Personality";
import type { Season } from "./Season";
import type { SelfState } from "./SelfState";
import type { Surroundings } from "./Surroundings";
import type { TimeOfDay } from "./TimeOfDay";
import type { Weather } from "./Weather";

/**
 * The complete perception payload delivered to an agent at the start of
 * each tick. This is everything the agent can "see."
 */
export type Perception = { 
/**
 * Current tick number.
 */
tick: bigint, 
/**
 * Current time of day.
 */
time_of_day: TimeOfDay, 
/**
 * Current season.
 */
season: Season, 
/**
 * Current weather.
 */
weather: Weather, 
/**
 * The agent's own state summary.
 */
self_state: SelfState, 
/**
 * What the agent can see at their current location.
 */
surroundings: Surroundings, 
/**
 * Routes the agent knows about from this location.
 */
known_routes: Array<KnownRoute>, 
/**
 * Relevant memories from the agent's memory system.
 */
recent_memory: Array<string>, 
/**
 * Actions the agent can currently perform.
 */
available_actions: Array<string>, 
/**
 * System notifications (approaching winter, low health, etc.).
 */
notifications: Array<string>, 
/**
 * The agent's personality traits (if known). Shapes decision-making.
 */
personality: Personality | null, };
