// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Immutable personality vector assigned at agent creation.
 *
 * Each trait is a [`Decimal`] in the range 0.0 to 1.0. Personality influences
 * decision-making but never changes over the agent's lifetime.
 */
export type Personality = { 
/**
 * Likelihood to explore, try new things, and learn from observation.
 */
curiosity: string, 
/**
 * Preference for collaboration versus solo action.
 */
cooperation: string, 
/**
 * Tendency toward conflict, competition, and dominance.
 */
aggression: string, 
/**
 * Willingness to take uncertain actions.
 */
risk_tolerance: string, 
/**
 * Preference for productive work versus rest or leisure.
 */
industriousness: string, 
/**
 * Desire for interaction versus solitude.
 */
sociability: string, 
/**
 * Tendency toward truthful communication.
 */
honesty: string, 
/**
 * Commitment to relationships and groups.
 */
loyalty: string, };
