// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentId } from "./AgentId";

/**
 * Population metrics for a world snapshot.
 */
export type PopulationStats = { 
/**
 * Number of living agents.
 */
total_alive: number, 
/**
 * Number of deceased agents.
 */
total_dead: number, 
/**
 * Agents born this tick.
 */
births_this_tick: number, 
/**
 * Agents who died this tick.
 */
deaths_this_tick: number, 
/**
 * Mean age of living agents.
 */
average_age: string, 
/**
 * Identifier of the longest-lived agent.
 */
oldest_agent: AgentId | null, };
