// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RejectionReason } from "./RejectionReason";

/**
 * Details of why an action was rejected, returned to the agent.
 */
export type RejectionDetails = { 
/**
 * The rejection reason code.
 */
reason: RejectionReason, 
/**
 * Human-readable explanation.
 */
message: string, };
