// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The reason an agent's action was rejected by the World Engine.
 */
export type RejectionReason = "InvalidAction" | "InsufficientEnergy" | "WrongLocation" | "InsufficientResources" | "UnavailableTarget" | "UnknownAction" | "ConflictLost" | "CapacityExceeded" | "InvalidTarget" | "PermissionDenied" | "Timeout" | "Infeasible" | "NeedsEvaluation" | "SameSexReproduction";
