// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentId } from "./AgentId";
import type { InteractionCause } from "./InteractionCause";

/**
 * Details for a relationship change event.
 *
 * Emitted whenever a relationship score is updated between two agents.
 */
export type RelationshipChangedDetails = { 
/**
 * First agent in the relationship.
 */
agent_a: AgentId, 
/**
 * Second agent in the relationship.
 */
agent_b: AgentId, 
/**
 * Score before the change.
 */
old_score: string, 
/**
 * Score after the change.
 */
new_score: string, 
/**
 * What caused the relationship to change.
 */
cause: InteractionCause, };
