// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LocationId } from "./LocationId";
import type { Resource } from "./Resource";

/**
 * Details for a resource gathered event.
 */
export type ResourceGatheredDetails = { 
/**
 * The type of resource gathered.
 */
resource: Resource, 
/**
 * Quantity gathered.
 */
quantity: number, 
/**
 * Location where gathering occurred.
 */
location_id: LocationId, 
/**
 * Skill experience points gained.
 */
skill_xp_gained: number, };
