// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Resource } from "./Resource";

/**
 * A resource source at a location with regeneration mechanics.
 */
export type ResourceNode = { 
/**
 * The type of resource at this node.
 */
resource: Resource, 
/**
 * Currently available quantity.
 */
available: number, 
/**
 * Units regenerated per tick.
 */
regen_per_tick: number, 
/**
 * Maximum quantity this node can hold.
 */
max_capacity: number, };
