// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A resource that exists in the simulation world.
 *
 * Resources are organized into tiers reflecting technological progression:
 * - Tier 0: Survival basics available from tick 0
 * - Tier 1: Developed resources requiring discovery or effort
 * - Tier 2: Advanced resources requiring multi-step processes
 * - Tier 3: Complex resources requiring civilization-level coordination
 */
export type Resource = "Water" | "FoodBerry" | "FoodFish" | "FoodRoot" | "FoodMeat" | "FoodFarmed" | "FoodCooked" | "Wood" | "Stone" | "Fiber" | "Clay" | "Hide" | "Ore" | "Metal" | "Medicine" | "Tool" | "ToolAdvanced" | "CurrencyToken" | "WrittenRecord";
