// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PathType } from "./PathType";
import type { RouteId } from "./RouteId";
import type { Weather } from "./Weather";

/**
 * Details for a route degraded event (durability reached zero).
 */
export type RouteDegradedDetails = { 
/**
 * The route that degraded.
 */
route_id: RouteId, 
/**
 * The previous path type before degradation.
 */
old_path_type: PathType, 
/**
 * The new path type after degradation.
 */
new_path_type: PathType, 
/**
 * Weather at the time of degradation.
 */
weather: Weather, };
