// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentId } from "./AgentId";
import type { PathType } from "./PathType";
import type { Resource } from "./Resource";
import type { RouteId } from "./RouteId";

/**
 * Details for a route improved event.
 */
export type RouteImprovedDetails = { 
/**
 * The route that was improved.
 */
route_id: RouteId, 
/**
 * The agent who performed the improvement.
 */
builder: AgentId, 
/**
 * The previous path type before the upgrade.
 */
old_path_type: PathType, 
/**
 * The new path type after the upgrade.
 */
new_path_type: PathType, 
/**
 * Materials consumed during the improvement.
 */
materials_used: { [key in Resource]?: number }, 
/**
 * Whether this was a repair (durability restore) rather than an upgrade.
 */
is_repair: boolean, 
/**
 * Durability restored (only relevant for repairs).
 */
durability_restored: number, };
