// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccessControlList } from "./AccessControlList";
import type { AgentId } from "./AgentId";
import type { LocationId } from "./LocationId";
import type { PathType } from "./PathType";
import type { RouteId } from "./RouteId";

/**
 * A directed edge connecting two locations in the world graph.
 */
export type Route = { 
/**
 * Unique route identifier.
 */
id: RouteId, 
/**
 * Origin location.
 */
from_location: LocationId, 
/**
 * Destination location.
 */
to_location: LocationId, 
/**
 * Travel time in ticks.
 */
cost_ticks: number, 
/**
 * Road quality.
 */
path_type: PathType, 
/**
 * Current condition (0--100).
 */
durability: number, 
/**
 * Maximum condition.
 */
max_durability: number, 
/**
 * Degradation rate per tick.
 */
decay_per_tick: string, 
/**
 * Access restrictions, if any.
 */
acl: AccessControlList | null, 
/**
 * Whether the route works in both directions.
 */
bidirectional: boolean, 
/**
 * Agent who built this route (`None` if natural).
 */
built_by: AgentId | null, 
/**
 * Tick when the route was built (`None` if natural).
 */
built_at_tick: bigint | null, };
