// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentId } from "./AgentId";
import type { GroupId } from "./GroupId";
import type { RuleId } from "./RuleId";

/**
 * A governance rule created by a group via the `Legislate` action.
 *
 * Rules are associated with a [`Group`] and created at a `MeetingHall`
 * structure. They represent social contracts that group members can
 * enforce against other agents.
 */
export type Rule = { 
/**
 * Unique rule identifier.
 */
id: RuleId, 
/**
 * The group that created this rule.
 */
group_id: GroupId, 
/**
 * The agent who proposed and created the rule.
 */
creator: AgentId, 
/**
 * Display name of the rule.
 */
name: string, 
/**
 * Detailed description of what the rule mandates or prohibits.
 */
description: string, 
/**
 * The tick when the rule was created.
 */
created_at_tick: bigint, 
/**
 * Whether the rule is currently active.
 */
active: boolean, };
