// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Unique identifier for a governance rule created via the `Legislate` action.
 */
export type RuleId = string;
