// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentId } from "./AgentId";
import type { GroupId } from "./GroupId";
import type { RuleId } from "./RuleId";

/**
 * Details for a rule created event.
 *
 * Emitted when an agent successfully creates a governance rule via
 * the `Legislate` action at a `MeetingHall`.
 */
export type RuleCreatedDetails = { 
/**
 * The unique ID of the new rule.
 */
rule_id: RuleId, 
/**
 * The group this rule belongs to.
 */
group_id: GroupId, 
/**
 * The agent who created the rule.
 */
creator: AgentId, 
/**
 * Display name of the rule.
 */
rule_name: string, 
/**
 * Description of the rule.
 */
rule_description: string, };
