// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A season in the simulation's annual cycle (90 ticks per season by default).
 */
export type Season = "Spring" | "Summer" | "Autumn" | "Winter";
