// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentId } from "./AgentId";
import type { Resource } from "./Resource";

/**
 * The agent's own state as presented in perception.
 *
 * This is a simplified, agent-facing view of the full [`AgentState`].
 *
 * [`AgentState`]: crate::structs::AgentState
 */
export type SelfState = { 
/**
 * The agent's identifier.
 */
id: AgentId, 
/**
 * The agent's name.
 */
name: string, 
/**
 * Current age in ticks.
 */
age: number, 
/**
 * Current energy (0--100).
 */
energy: number, 
/**
 * Current health (0--100).
 */
health: number, 
/**
 * Current hunger (0--100).
 */
hunger: number, 
/**
 * Name of the agent's current location.
 */
location_name: string, 
/**
 * Inventory contents.
 */
inventory: { [key in Resource]?: number }, 
/**
 * Carry load as a formatted string (e.g. "26/50").
 */
carry_load: string, 
/**
 * Current active goals.
 */
active_goals: Array<string>, 
/**
 * Known skills with level (e.g. "gathering (lvl 4)").
 */
known_skills: Array<string>, };
