// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Biological sex of an agent, used for sexual reproduction requirements.
 *
 * Every agent is assigned a sex at creation (randomly for seed agents,
 * randomly for children). Reproduction requires one `Male` and one `Female`
 * partner.
 */
export type Sex = "Male" | "Female";
