// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LocationId } from "./LocationId";
import type { Resource } from "./Resource";
import type { StructureId } from "./StructureId";
import type { StructureType } from "./StructureType";

/**
 * Details for a structure destroyed event.
 *
 * Covers both collapse from decay and demolition by an agent.
 */
export type StructureDestroyedDetails = { 
/**
 * The structure that was destroyed.
 */
structure_id: StructureId, 
/**
 * The type of structure that was destroyed.
 */
structure_type: StructureType, 
/**
 * The location where the structure stood.
 */
location_id: LocationId, 
/**
 * How the structure was destroyed.
 */
cause: string, 
/**
 * Materials salvaged (30% of original, returned to agent or location).
 */
materials_salvaged: { [key in Resource]?: number }, };
