// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Resource } from "./Resource";

/**
 * Type-specific properties attached to a structure.
 */
export type StructureProperties = { 
/**
 * Multiplier for rest recovery when sheltering in this structure.
 */
rest_bonus: string, 
/**
 * Whether this structure blocks weather effects.
 */
weather_protection: boolean, 
/**
 * Additional inventory storage slots provided.
 */
storage_slots: number, 
/**
 * The resource this structure produces, if any.
 */
production_type: Resource | null, 
/**
 * Units produced per tick.
 */
production_rate: number, };
