// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccessControlList } from "./AccessControlList";
import type { AgentId } from "./AgentId";
import type { LocationId } from "./LocationId";
import type { Resource } from "./Resource";
import type { StructureId } from "./StructureId";
import type { StructureProperties } from "./StructureProperties";
import type { StructureType } from "./StructureType";

/**
 * A persistent structure built by an agent at a location.
 */
export type Structure = { 
/**
 * Unique structure identifier.
 */
id: StructureId, 
/**
 * The type of structure.
 */
structure_type: StructureType, 
/**
 * Specific variant within the type.
 */
subtype: string | null, 
/**
 * Location where this structure exists.
 */
location_id: LocationId, 
/**
 * Agent who built this structure.
 */
builder: AgentId, 
/**
 * Current owner (`None` if unowned).
 */
owner: AgentId | null, 
/**
 * Tick when the structure was built.
 */
built_at_tick: bigint, 
/**
 * Tick when the structure was destroyed (`None` if standing).
 */
destroyed_at_tick: bigint | null, 
/**
 * Materials used to construct this structure.
 */
materials_used: { [key in Resource]?: number }, 
/**
 * Current condition (0--100).
 */
durability: number, 
/**
 * Maximum condition.
 */
max_durability: number, 
/**
 * Degradation rate per tick.
 */
decay_per_tick: string, 
/**
 * Maximum occupant count.
 */
capacity: number, 
/**
 * Current occupants.
 */
occupants: Array<AgentId>, 
/**
 * Access restrictions, if any.
 */
access_list: AccessControlList | null, 
/**
 * Type-specific properties.
 */
properties: StructureProperties, };
