// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentId } from "./AgentId";
import type { LocationId } from "./LocationId";
import type { StructureId } from "./StructureId";
import type { StructureType } from "./StructureType";

/**
 * Details for a structure claimed event.
 *
 * Emitted when an agent takes ownership of an unowned or orphaned structure.
 */
export type StructureClaimedDetails = { 
/**
 * The structure that was claimed.
 */
structure_id: StructureId, 
/**
 * The type of structure that was claimed.
 */
structure_type: StructureType, 
/**
 * The agent who claimed the structure.
 */
new_owner: AgentId, 
/**
 * The previous owner, if any (dead agent whose ownership lapsed).
 */
previous_owner: AgentId | null, 
/**
 * The location where the structure exists.
 */
location_id: LocationId, };
