// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentId } from "./AgentId";
import type { Resource } from "./Resource";
import type { StructureId } from "./StructureId";

/**
 * Details for a structure repaired event.
 */
export type StructureRepairedDetails = { 
/**
 * The structure that was repaired.
 */
structure_id: StructureId, 
/**
 * The agent who performed the repair.
 */
repairer: AgentId, 
/**
 * Durability before the repair.
 */
durability_before: number, 
/**
 * Durability after the repair.
 */
durability_after: number, 
/**
 * Materials consumed during repair.
 */
materials_used: { [key in Resource]?: number }, };
