// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentId } from "./AgentId";
import type { LocationId } from "./LocationId";
import type { Resource } from "./Resource";
import type { StructureId } from "./StructureId";
import type { StructureType } from "./StructureType";

/**
 * Details for a structure built event.
 */
export type StructureBuiltDetails = { 
/**
 * The unique ID of the newly built structure.
 */
structure_id: StructureId, 
/**
 * The type of structure that was built.
 */
structure_type: StructureType, 
/**
 * The location where the structure was built.
 */
location_id: LocationId, 
/**
 * The agent who built it.
 */
builder: AgentId, 
/**
 * Materials consumed during construction.
 */
materials_used: { [key in Resource]?: number }, };
