// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Resource } from "./Resource";
import type { StructureCategory } from "./StructureCategory";
import type { StructureProperties } from "./StructureProperties";
import type { StructureType } from "./StructureType";

/**
 * A blueprint defining the cost, properties, and requirements for building
 * a specific [`StructureType`].
 *
 * Blueprints are static data looked up by structure type. They define what
 * materials are required, what knowledge the builder needs, and the
 * properties of the resulting structure.
 */
export type StructureBlueprint = { 
/**
 * The structure type this blueprint produces.
 */
structure_type: StructureType, 
/**
 * Functional category of the structure.
 */
category: StructureCategory, 
/**
 * Material costs required to build this structure.
 */
material_costs: { [key in Resource]?: number }, 
/**
 * Knowledge concept the builder must possess.
 */
required_knowledge: string, 
/**
 * Maximum durability of the completed structure.
 */
max_durability: number, 
/**
 * Durability lost per tick due to natural decay.
 */
decay_per_tick: string, 
/**
 * Maximum number of occupants.
 */
capacity: number, 
/**
 * Properties of the completed structure.
 */
properties: StructureProperties, };
