// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The functional category of a structure.
 *
 * Determines the primary purpose of the structure within the simulation.
 */
export type StructureCategory = "Utility" | "Shelter" | "Storage" | "Production" | "Social" | "Knowledge" | "Economic" | "Defense" | "Infrastructure";
