// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A type of structure that can be built at a location.
 */
export type StructureType = "Campfire" | "LeanTo" | "BasicHut" | "StoragePit" | "Well" | "FarmPlot" | "Workshop" | "MeetingHall" | "Forge" | "Library" | "Market" | "Wall" | "Bridge";
