// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Resource } from "./Resource";
import type { VisibleAgent } from "./VisibleAgent";
import type { VisibleMessage } from "./VisibleMessage";
import type { VisibleStructure } from "./VisibleStructure";

/**
 * What the agent can see at their current location.
 */
export type Surroundings = { 
/**
 * Narrative description of the location.
 */
location_description: string, 
/**
 * Fuzzy resource quantities (e.g. "abundant", "scarce").
 */
visible_resources: { [key in Resource]?: string }, 
/**
 * Structures present at this location.
 */
structures_here: Array<VisibleStructure>, 
/**
 * Other agents present at this location.
 */
agents_here: Array<VisibleAgent>, 
/**
 * Broadcast messages posted at this location.
 */
messages_here: Array<VisibleMessage>, };
