// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentId } from "./AgentId";
import type { LocationId } from "./LocationId";
import type { Resource } from "./Resource";

/**
 * Details for a successful theft event.
 *
 * Emitted when an agent successfully steals resources from another agent
 * at the same location. The stolen resources are transferred via the
 * central ledger with entry type `Theft`.
 */
export type TheftOccurredDetails = { 
/**
 * The agent who committed the theft.
 */
thief_id: AgentId, 
/**
 * The agent who was stolen from.
 */
victim_id: AgentId, 
/**
 * The resource that was stolen.
 */
resource: Resource, 
/**
 * The quantity stolen.
 */
quantity_stolen: number, 
/**
 * Whether the victim detected the thief.
 */
detected: boolean, 
/**
 * The location where the theft occurred.
 */
location_id: LocationId, };
