// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentId } from "./AgentId";
import type { LocationId } from "./LocationId";
import type { Resource } from "./Resource";
import type { TheftFailureReason } from "./TheftFailureReason";

/**
 * Details for a failed theft event.
 *
 * Emitted when a theft attempt fails. If the victim detected the attempt,
 * they will be notified in the next perception cycle and the relationship
 * will be damaged.
 */
export type TheftFailedDetails = { 
/**
 * The agent who attempted the theft.
 */
thief_id: AgentId, 
/**
 * The agent who was the target.
 */
victim_id: AgentId, 
/**
 * The resource the thief was trying to steal.
 */
target_resource: Resource, 
/**
 * Why the theft failed.
 */
reason: TheftFailureReason, 
/**
 * Whether the victim detected the attempt.
 */
detected: boolean, 
/**
 * The location where the attempt occurred.
 */
location_id: LocationId, };
