// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The reason a theft attempt failed.
 */
export type TheftFailureReason = "VictimNotPresent" | "VictimHasNoResource" | "Caught" | "InsufficientSkill";
