// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The time of day within a single tick.
 */
export type TimeOfDay = "Dawn" | "Morning" | "Afternoon" | "Dusk" | "Night";
