// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentId } from "./AgentId";
import type { Resource } from "./Resource";
import type { TradeId } from "./TradeId";

/**
 * Details for a completed trade event.
 */
export type TradeCompletedDetails = { 
/**
 * Unique trade identifier.
 */
trade_id: TradeId, 
/**
 * First trading party.
 */
agent_a: AgentId, 
/**
 * Second trading party.
 */
agent_b: AgentId, 
/**
 * Resources given by agent A.
 */
gave: { [key in Resource]?: number }, 
/**
 * Resources received by agent A.
 */
received: { [key in Resource]?: number }, };
