// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentId } from "./AgentId";
import type { TradeFailReason } from "./TradeFailReason";
import type { TradeId } from "./TradeId";

/**
 * Details for a failed trade event.
 */
export type TradeFailedDetails = { 
/**
 * Unique trade identifier.
 */
trade_id: TradeId, 
/**
 * Why the trade failed.
 */
reason: TradeFailReason, 
/**
 * Agent who proposed the trade.
 */
offerer_id: AgentId, 
/**
 * Agent who was the target.
 */
target_id: AgentId, };
