// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The reason a trade failed.
 */
export type TradeFailReason = "Rejected" | "Expired" | "InsufficientResources" | "NotCoLocated" | "NotFound";
