// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Sex } from "./Sex";

/**
 * Another agent as seen in the perception's surroundings.
 */
export type VisibleAgent = { 
/**
 * The other agent's name.
 */
name: string, 
/**
 * The other agent's biological sex.
 */
sex: Sex, 
/**
 * Relationship description (e.g. "friendly (0.7)").
 */
relationship: string, 
/**
 * What the agent appears to be doing.
 */
activity: string, };
