// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A broadcast message visible at a location.
 */
export type VisibleMessage = { 
/**
 * Who sent the message.
 */
from: string, 
/**
 * The tick the message was sent.
 */
tick: bigint, 
/**
 * Message content.
 */
content: string, };
