// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Details for a visible structure in perception surroundings.
 */
export type VisibleStructure = { 
/**
 * The type of structure (e.g. "shelter (basic hut)").
 */
structure_type: string, 
/**
 * Who owns it.
 */
owner: string, 
/**
 * Current durability as a percentage string.
 */
durability: string, 
/**
 * Names of occupants.
 */
occupants: Array<string>, };
