// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Current weather conditions affecting travel, structures, and farming.
 */
export type Weather = "Clear" | "Rain" | "Storm" | "Drought" | "Snow";
