// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EconomyStats } from "./EconomyStats";
import type { Era } from "./Era";
import type { PopulationStats } from "./PopulationStats";
import type { Season } from "./Season";
import type { Weather } from "./Weather";

/**
 * End-of-tick summary of the world state.
 */
export type WorldSnapshot = { 
/**
 * The tick this snapshot represents.
 */
tick: bigint, 
/**
 * Current civilizational era.
 */
era: Era, 
/**
 * Current season.
 */
season: Season, 
/**
 * Current weather.
 */
weather: Weather, 
/**
 * Population metrics.
 */
population: PopulationStats, 
/**
 * Economic metrics.
 */
economy: EconomyStats, 
/**
 * All discoveries made to date.
 */
discoveries: Array<string>, 
/**
 * Narrative summary of the tick.
 */
summary: string, };
