// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Era } from "./Era";
import type { Season } from "./Season";
import type { Weather } from "./Weather";

/**
 * Snapshot of world-level state attached to events.
 */
export type WorldContext = { 
/**
 * Current tick number.
 */
tick: bigint, 
/**
 * Current civilizational era.
 */
era: Era, 
/**
 * Current season.
 */
season: Season, 
/**
 * Current weather.
 */
weather: Weather, 
/**
 * Number of living agents.
 */
population: number, };
